{% set version = "1.2.0" %}

package:
  name: fft-conv-pytorch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fft-conv-pytorch/fft-conv-pytorch-{{ version }}.tar.gz
  sha256: 9a061383176fa72cb2d8815d0c9ae67d03f7f1cea182ec9b9f5e869168582adb

build:
  noarch: python
  script: 
    # While the noarch builds run on linux, this just helps in the future case where
    # there may be some architecture dependence
    - set FFT_CONV_PYTORCH_VERSION={{ version }}      # [win]
    - export FFT_CONV_PYTORCH_VERSION={{ version }}   # [unix]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pytorch >=1.8

test:
  imports:
    - fft_conv_pytorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fkodom/fft-conv-pytorch
  summary: Implementation of 1D, 2D, and 3D FFT convolutions in PyTorch.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
